[build]
  publish = "dist"               # where vite/react build outputs
  functions = "netlify/functions"   # folder for serverless functions

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
